# Generated by Django 6.1.1 on 2026-10-03 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'luogo',
                'verbose_name_plural': 'luoghi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('inventory_code', models.CharField(max_length=50, unique=True, verbose_name='codice inventario')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('in_use', 'In uso'), ('retired', 'Dismesso')], default='available', max_length=20, verbose_name='stato')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='data di acquisto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='inserito il')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_assets', to=settings.AUTH_USER_MODEL, verbose_name='responsabile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.category', verbose_name='categoria')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.location', verbose_name='luogo')),
            ],
            options={
                'verbose_name': 'bene',
                'verbose_name_plural': 'beni',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Inserito'), ('checked_out', 'Preso in carico'), ('returned', 'Restituito'), ('moved', 'Spostato'), ('retired', 'Dismesso')], max_length=20, verbose_name='azione')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='nota')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='data e ora')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets.asset', verbose_name='bene')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.location', verbose_name='da')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.location', verbose_name='a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'movimento',
                'verbose_name_plural': 'movimenti',
                'ordering': ['-timestamp'],
            },
        ),
    ]
